# Generated by Django 4.2.16 on 2024-09-27 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_task",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("work", "Work"),
                    ("urgent", "Urgent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("0", "Low"), ("1", "Medium"), ("2", "High")], max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("ns", "Not Started!"),
                    ("wip", "Work In Progress"),
                    ("done", "Completed!"),
                ],
                max_length=32,
            ),
        ),
    ]
