# Generated by Django 4.2.16 on 2024-10-02 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0002_task_assigned_to_alter_task_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                default=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="task",
                    to=settings.AUTH_USER_MODEL,
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
